using CartonCaps.Domain.Common;

namespace CartonCaps.Domain.Entities;

/// <summary>
/// Represents a user entity in the system.
/// </summary>
/// <remarks>Inherits from <see cref="BaseEntity"/>.</remarks>
/// <seealso cref="BaseEntity"/>
public sealed class User : BaseEntity
{
    /// <summary>
    /// The unique identifier for the user.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// The user's first name.
    /// </summary>
    /// <returns>A string containing the user's first name.</returns>
    public required string FirstName { get; set; }

    /// <summary>
    /// The user's last name.
    /// </summary>
    /// <returns>A string containing the user's last name.</returns>
    public required string LastName { get; set; }
    // Represents the user's full name in a short format, e.g., "Josie P."
    /// <summary>
    /// The user's first and last name in a short format.
    /// </summary>
    /// <returns>A string containing the user's first and last name.</returns>
    /// <example>Debbie H.</example>
    public string ShortDisplayName
    {
        get => $"{FirstName} {LastName.First()}.";
    }

    /// <summary>
    /// The user's email address.
    /// </summary>
    /// <returns>A string containing the user's email address.</returns>
    public required string Email { get; set; }
    // ReferralCode is a unique code generated for each user to share with others

    /// <summary>
    /// The user's referral code, which is a unique identifier for the user.
    /// </summary>
    /// <returns>A string containing the user's referral code.</returns>
    /// <example>ABC123</example>
    /// <remarks>This code is used to track referrals made by the user and is generated by a different API</remarks>
    public required string ReferralCode { get; set; }
}